[package]
name = "keystr-rs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
hex = "0.4.3"
iced = "0.7.0"
nostr = "0.18.0"
readonly = "0.2.3"
serde_json = "1.0.93"
thiserror = "1.0"
