name: Linux CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: |
        sudo apt-get update && sudo apt-get install rustc --fix-missing
        rustc --version
    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          rust
    - name: Build
      run: |
        cargo build
    - name: Running tests
      run: |
        cargo test
